version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5003:5000"      
  db:
    #image: mysql:5.7
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    #security_opt:
    #  - seccomp:unconfined
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  jwt:
    build:
      context: ./jwt-server
      dockerfile: node.dockerfile
    ports:
      - "5004:5000"
    volumes:
      - ./publickeys:/home/publickeys 
    networks:
      - jwt-network
      - traducciones-network
    depends_on: 
      - jwtdb

  jwtdb:
    image: mongo
    networks:
      - jwt-network

networks:
  jwt-network:
    driver: bridge
  traducciones-network:
    driver: bridge